# Generated by Django 3.1.7 on 2021-03-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_add_activate_and_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='pd_num',
            field=models.CharField(db_index=True, max_length=200, verbose_name='상품번호'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pd_num',
            field=models.CharField(max_length=200, unique=True, verbose_name='상품번호'),
        ),
    ]
