# Generated by Django 3.1.7 on 2021-03-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_product_pd_num_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='kind',
            field=models.CharField(choices=[('', 'Null'), ('coffee', 'Coffee'), ('tea', 'Tea'), ('MD_product', 'Md'), ('frappuccino', 'Frappuccino'), ('blended', 'Blended')], default='', max_length=20, verbose_name='상품 종류'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='pd_num',
            field=models.CharField(db_index=True, max_length=30, verbose_name='상품번호'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('', 'Null'), ('coffee', 'Coffee'), ('tea', 'Tea'), ('MD_product', 'Md'), ('frappuccino', 'Frappuccino'), ('blended', 'Blended')], default='', max_length=20, verbose_name='상품 종류'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pd_num',
            field=models.CharField(max_length=30, unique=True, verbose_name='상품번호'),
        ),
    ]
