# Generated by Django 3.1.7 on 2021-03-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='complain',
            field=models.CharField(blank=True, max_length=200, verbose_name='불편사항'),
        ),
        migrations.AlterField(
            model_name='order',
            name='complain',
            field=models.CharField(blank=True, max_length=200, verbose_name='불편사항'),
        ),
    ]
