# Generated by Django 3.1.7 on 2021-03-18 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('paymentWay', models.CharField(choices=[('money', 'Money'), ('credit card', 'Credit Card')], default='money', max_length=20, verbose_name='결제 수단')),
                ('cardName', models.CharField(default=None, max_length=30, verbose_name='주문 카드')),
                ('point', models.IntegerField(default=None, verbose_name='포인트')),
                ('ordererPay', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orderer_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '주문 처리 관련',
                'verbose_name_plural': '주문 관련 리스트',
            },
        ),
    ]
