# Generated by Django 3.1.7 on 2021-03-19 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_auto_20210318_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ordererPay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordererPay_set', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentWay',
            field=models.CharField(choices=[('money', 'Money'), ('credit card', 'Credit Card')], default='', max_length=20, verbose_name='결제 수단'),
        ),
    ]
