# Generated by Django 3.1.7 on 2021-03-20 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0003_auto_20210319_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ordererPay',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordererPay_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentWay',
            field=models.CharField(blank=True, choices=[('money', 'Money'), ('credit card', 'Credit Card')], default='', max_length=20, verbose_name='결제 수단'),
        ),
    ]
