# Generated by Django 3.1.7 on 2021-03-20 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0004_auto_20210320_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ordererPay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordererPay_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
